SSL everywhere
wmo-im/wis2box pull request #403
Opened 2023-02-22 08:38 UTC by maaikelimper

Here's my first attempt at implementing SSL everywhere.

Basically I add add additional docker-compose-file to allow a user to share the SSL-cert and SSL-key with the nginx and mosquitto container. 

To enable HTTPS and MQTTS on your wis2box run wis2box with the option '--ssl':

.. code-block:: bash

   python3 wis2box-ctl.py --ssl start

Which requires additional environment variables in dev.env:

.. code-block:: bash

  WIS2BOX_SSL_CERT=/etc/letsencrypt/live/example.wis2box.io/fullchain.pem
  WIS2BOX_SSL_KEY=/etc/letsencrypt/live/example.wis2box.io/privkey.pem

2023-02-22 08:47 UTC, maaikelimper commented
This branch is currently running wis2box-zambia for testing:

https://zambia.wis2box.io

mosquitto_sub -d -L mqtts://everyone:everyone@zambia.wis2box.io/origin/#

2023-03-03 19:01 UTC, tomkralidis requested changes

2023-03-07 02:04 UTC, tomkralidis commented
@maaikelimper can you rebase against latest main (changes since last update)?

2023-03-07 13:41 UTC, tomkralidis approved these changes

2023-03-07 13:41 UTC, merged