[WIP] add option to publish specific stations to a certain topic (#720)
wmo-im/wis2box pull request #723
Opened 2024-08-07 02:23 UTC by tomkralidis

2024-08-08 11:45 UTC, tomkralidis commented
- remove hardcoded STATION path (overall)

2024-08-14 12:01 UTC, tomkralidis commented
Update CI to run topic hierarchy addition in lieu of running station publication twice.

2024-08-15 07:35 UTC, maaikelimper commented on docs/source/user/setup.rst
>  After doing a bulk insert please review the stations in wis2box-webapp and associate each station to the correct topics.
Can you please update the documentation to include the topic-association during the bulk-insert ? I am not sure what is the use-case for having station metadata in wis2box for stations that are not associated to WIS2-topic to be published, so adding a topic during the bulk-insert should be the baseline.

2024-08-15 07:37 UTC, maaikelimper requested changes

2024-08-15 07:37 UTC, maaikelimper commented on .github/workflows/tests-docker.yml
> +        python3 wis2box-ctl.py execute wis2box metadata station publish-collection --path /data/wis2box/metadata/station/station_list.csv
can we split the station-list into separate files per test dataset, remove the step "populate stations from CSV" and instead add one bulk-insert command for each dataset being tested ?

2024-08-19 11:55 UTC, maaikelimper approved these changes

2024-08-19 11:55 UTC, merged