wis2downloader - pull from ghcr
wmo-im/wis2box pull request #742
Opened 2024-08-22 09:04 UTC by david-i-berry

- Update to pull wis2downloader from GHCR and to use latest version of the downloader.
- Update to tests and create config for new workflow associated with init of downloader.

2024-08-22 09:10 UTC, maaikelimper requested changes

2024-08-22 09:10 UTC, maaikelimper commented on .github/workflows/tests-docker.yml
> +        echo "DOWNLOADER_UID=12135" >> tests/test.env
as discussed DOWNLOADER_UID can not be used as an environment variable but has to be set to 12135 for the downloader-image to run

2024-08-22 15:09 UTC, maaikelimper approved these changes

2024-08-22 18:05 UTC, maaikelimper approved these changes

2024-08-23 00:48 UTC, tomkralidis approved these changes

2024-08-23 00:48 UTC, merged