Include additional UI variables in docs
wmo-im/wis2box pull request #824
Opened 2024-12-20 03:15 UTC by webb-ben

Includes additional environment variables to the docs as implemented in https://github.com/wmo-im/wis2box-ui/pull/95

Addresses:
https://github.com/wmo-im/wis2box-ui/issues/93
https://github.com/wmo-im/wis2box-ui/issues/98

2024-12-20 18:46 UTC, webb-ben commented
Ready for review after: https://github.com/wmo-im/wis2box-ui/pull/103

2024-12-21 13:42 UTC, tomkralidis commented
FYI https://github.com/wmo-im/wis2box-ui/pull/103 is now merged.  Let me know when ready for review/out of draft.

2024-12-21 14:40 UTC, tomkralidis requested changes

2024-12-21 14:40 UTC, tomkralidis commented on wis2box-create-config.py
> +            return logo if logo else None
```python
return logo or None
```

2024-12-21 14:40 UTC, tomkralidis commented on wis2box-create-config.py
> +def get_default_ui_language():
```python
def get_default_ui_language() -> Union[str, None]:
```

Note that you will need to update `from typing import Tuple` to `from typing import Tuple, Union` on line 29.

2024-12-21 14:40 UTC, tomkralidis commented on docs/source/reference/configuration.rst
> +Web application configuration provides the ability to customize web components. All of these are optional.
Web application configuration provides the ability to customize web components. All of the below directives are optional.

2024-12-21 14:55 UTC, tomkralidis approved these changes

2024-12-21 14:55 UTC, merged